//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.12 at 07:50:41 PM BST 
//


package walla.datatypes.auto;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="AccountActionRef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="ActionDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NumTimes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ActionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GalleryActionRef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="GalleryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GalleryDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ViewTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ViewMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UserAppRef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="UserAppId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="AppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MachineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Blocked" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="LastUsed" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="UserAppActionRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="ActionDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NumTimes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "action",
    "actionId",
    "accountActionRef",
    "galleryActionRef",
    "userAppRef"
})
@XmlRootElement(name = "AccountActionSummary", namespace = "http://ws.fotowalla.com/AccountActionSummary")
public class AccountActionSummary {

    @XmlElement(name = "Action", namespace = "http://ws.fotowalla.com/AccountActionSummary", required = true)
    protected String action;
    @XmlElement(name = "ActionId", namespace = "http://ws.fotowalla.com/AccountActionSummary")
    protected long actionId;
    @XmlElement(name = "AccountActionRef", namespace = "http://ws.fotowalla.com/AccountActionSummary")
    protected List<AccountActionSummary.AccountActionRef> accountActionRef;
    @XmlElement(name = "GalleryActionRef", namespace = "http://ws.fotowalla.com/AccountActionSummary")
    protected List<AccountActionSummary.GalleryActionRef> galleryActionRef;
    @XmlElement(name = "UserAppRef", namespace = "http://ws.fotowalla.com/AccountActionSummary")
    protected List<AccountActionSummary.UserAppRef> userAppRef;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the actionId property.
     * 
     */
    public long getActionId() {
        return actionId;
    }

    /**
     * Sets the value of the actionId property.
     * 
     */
    public void setActionId(long value) {
        this.actionId = value;
    }

    /**
     * Gets the value of the accountActionRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountActionRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountActionRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountActionSummary.AccountActionRef }
     * 
     * 
     */
    public List<AccountActionSummary.AccountActionRef> getAccountActionRef() {
        if (accountActionRef == null) {
            accountActionRef = new ArrayList<AccountActionSummary.AccountActionRef>();
        }
        return this.accountActionRef;
    }

    /**
     * Gets the value of the galleryActionRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the galleryActionRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGalleryActionRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountActionSummary.GalleryActionRef }
     * 
     * 
     */
    public List<AccountActionSummary.GalleryActionRef> getGalleryActionRef() {
        if (galleryActionRef == null) {
            galleryActionRef = new ArrayList<AccountActionSummary.GalleryActionRef>();
        }
        return this.galleryActionRef;
    }

    /**
     * Gets the value of the userAppRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userAppRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserAppRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountActionSummary.UserAppRef }
     * 
     * 
     */
    public List<AccountActionSummary.UserAppRef> getUserAppRef() {
        if (userAppRef == null) {
            userAppRef = new ArrayList<AccountActionSummary.UserAppRef>();
        }
        return this.userAppRef;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="ActionDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NumTimes" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ActionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "actionDesc",
        "numTimes",
        "actionDate"
    })
    public static class AccountActionRef {

        @XmlElement(name = "ActionDesc", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected String actionDesc;
        @XmlElement(name = "NumTimes", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected Integer numTimes;
        @XmlElement(name = "ActionDate", namespace = "http://ws.fotowalla.com/AccountActionSummary", type = String.class)
        @XmlJavaTypeAdapter(Adapter1 .class)
        @XmlSchemaType(name = "dateTime")
        protected Calendar actionDate;

        /**
         * Gets the value of the actionDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActionDesc() {
            return actionDesc;
        }

        /**
         * Sets the value of the actionDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionDesc(String value) {
            this.actionDesc = value;
        }

        /**
         * Gets the value of the numTimes property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumTimes() {
            return numTimes;
        }

        /**
         * Sets the value of the numTimes property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumTimes(Integer value) {
            this.numTimes = value;
        }

        /**
         * Gets the value of the actionDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Calendar getActionDate() {
            return actionDate;
        }

        /**
         * Sets the value of the actionDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionDate(Calendar value) {
            this.actionDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="GalleryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GalleryDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ViewTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ViewMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "galleryName",
        "galleryDesc",
        "viewTotal",
        "viewMonth"
    })
    public static class GalleryActionRef {

        @XmlElement(name = "GalleryName", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected String galleryName;
        @XmlElement(name = "GalleryDesc", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected String galleryDesc;
        @XmlElement(name = "ViewTotal", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected Integer viewTotal;
        @XmlElement(name = "ViewMonth", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected Integer viewMonth;

        /**
         * Gets the value of the galleryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGalleryName() {
            return galleryName;
        }

        /**
         * Sets the value of the galleryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGalleryName(String value) {
            this.galleryName = value;
        }

        /**
         * Gets the value of the galleryDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGalleryDesc() {
            return galleryDesc;
        }

        /**
         * Sets the value of the galleryDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGalleryDesc(String value) {
            this.galleryDesc = value;
        }

        /**
         * Gets the value of the viewTotal property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getViewTotal() {
            return viewTotal;
        }

        /**
         * Sets the value of the viewTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setViewTotal(Integer value) {
            this.viewTotal = value;
        }

        /**
         * Gets the value of the viewMonth property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getViewMonth() {
            return viewMonth;
        }

        /**
         * Sets the value of the viewMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setViewMonth(Integer value) {
            this.viewMonth = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="UserAppId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="AppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MachineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Blocked" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="LastUsed" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="UserAppActionRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="ActionDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NumTimes" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userAppId",
        "appName",
        "platform",
        "machineName",
        "blocked",
        "lastUsed",
        "userAppActionRef"
    })
    public static class UserAppRef {

        @XmlElement(name = "UserAppId", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected Long userAppId;
        @XmlElement(name = "AppName", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected String appName;
        @XmlElement(name = "Platform", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected String platform;
        @XmlElement(name = "MachineName", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected String machineName;
        @XmlElement(name = "Blocked", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected Boolean blocked;
        @XmlElement(name = "LastUsed", namespace = "http://ws.fotowalla.com/AccountActionSummary", type = String.class)
        @XmlJavaTypeAdapter(Adapter1 .class)
        @XmlSchemaType(name = "dateTime")
        protected Calendar lastUsed;
        @XmlElement(name = "UserAppActionRef", namespace = "http://ws.fotowalla.com/AccountActionSummary")
        protected List<AccountActionSummary.UserAppRef.UserAppActionRef> userAppActionRef;

        /**
         * Gets the value of the userAppId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getUserAppId() {
            return userAppId;
        }

        /**
         * Sets the value of the userAppId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setUserAppId(Long value) {
            this.userAppId = value;
        }

        /**
         * Gets the value of the appName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAppName() {
            return appName;
        }

        /**
         * Sets the value of the appName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAppName(String value) {
            this.appName = value;
        }

        /**
         * Gets the value of the platform property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlatform() {
            return platform;
        }

        /**
         * Sets the value of the platform property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlatform(String value) {
            this.platform = value;
        }

        /**
         * Gets the value of the machineName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMachineName() {
            return machineName;
        }

        /**
         * Sets the value of the machineName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMachineName(String value) {
            this.machineName = value;
        }

        /**
         * Gets the value of the blocked property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean getBlocked() {
            return blocked;
        }

        /**
         * Sets the value of the blocked property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBlocked(Boolean value) {
            this.blocked = value;
        }

        /**
         * Gets the value of the lastUsed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Calendar getLastUsed() {
            return lastUsed;
        }

        /**
         * Sets the value of the lastUsed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUsed(Calendar value) {
            this.lastUsed = value;
        }

        /**
         * Gets the value of the userAppActionRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userAppActionRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserAppActionRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AccountActionSummary.UserAppRef.UserAppActionRef }
         * 
         * 
         */
        public List<AccountActionSummary.UserAppRef.UserAppActionRef> getUserAppActionRef() {
            if (userAppActionRef == null) {
                userAppActionRef = new ArrayList<AccountActionSummary.UserAppRef.UserAppActionRef>();
            }
            return this.userAppActionRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="ActionDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NumTimes" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "actionDesc",
            "numTimes",
            "actionDate"
        })
        public static class UserAppActionRef {

            @XmlElement(name = "ActionDesc", namespace = "http://ws.fotowalla.com/AccountActionSummary")
            protected String actionDesc;
            @XmlElement(name = "NumTimes", namespace = "http://ws.fotowalla.com/AccountActionSummary")
            protected Integer numTimes;
            @XmlElement(name = "ActionDate", namespace = "http://ws.fotowalla.com/AccountActionSummary", type = String.class)
            @XmlJavaTypeAdapter(Adapter1 .class)
            @XmlSchemaType(name = "dateTime")
            protected Calendar actionDate;

            /**
             * Gets the value of the actionDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActionDesc() {
                return actionDesc;
            }

            /**
             * Sets the value of the actionDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActionDesc(String value) {
                this.actionDesc = value;
            }

            /**
             * Gets the value of the numTimes property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNumTimes() {
                return numTimes;
            }

            /**
             * Sets the value of the numTimes property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNumTimes(Integer value) {
                this.numTimes = value;
            }

            /**
             * Gets the value of the actionDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public Calendar getActionDate() {
                return actionDate;
            }

            /**
             * Sets the value of the actionDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActionDate(Calendar value) {
                this.actionDate = value;
            }

        }

    }

}
