//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.17 at 07:12:07 PM GMT 
//


package walla.datatypes.auto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="ProfileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Timezone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Newsletter" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AccountMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AccountTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PasswordChangeDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="OpenDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CloseDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Emails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EmailRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Principle" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="Secondary" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="Verified" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StorageSummary">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StorageGBLimit" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="MonthlyUploadCap" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="UploadCount30Days" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="FormatRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="UploadSourceRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ImageYearRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "profileName",
    "desc",
    "country",
    "timezone",
    "newsletter",
    "password",
    "status",
    "accountMessage",
    "accountType",
    "accountTypeName",
    "passwordChangeDate",
    "openDate",
    "closeDate",
    "key",
    "securityMessage",
    "emails",
    "storageSummary"
})
@XmlRootElement(name = "Account", namespace = "http://ws.fotowalla.com/Account")
public class Account {

    @XmlElement(name = "ProfileName", namespace = "http://ws.fotowalla.com/Account")
    protected String profileName;
    @XmlElement(name = "Desc", namespace = "http://ws.fotowalla.com/Account")
    protected String desc;
    @XmlElement(name = "Country", namespace = "http://ws.fotowalla.com/Account")
    protected String country;
    @XmlElement(name = "Timezone", namespace = "http://ws.fotowalla.com/Account")
    protected String timezone;
    @XmlElement(name = "Newsletter", namespace = "http://ws.fotowalla.com/Account")
    protected Boolean newsletter;
    @XmlElement(name = "Password", namespace = "http://ws.fotowalla.com/Account")
    protected String password;
    @XmlElement(name = "Status", namespace = "http://ws.fotowalla.com/Account")
    protected Integer status;
    @XmlElement(name = "AccountMessage", namespace = "http://ws.fotowalla.com/Account")
    protected String accountMessage;
    @XmlElement(name = "AccountType", namespace = "http://ws.fotowalla.com/Account")
    protected Integer accountType;
    @XmlElement(name = "AccountTypeName", namespace = "http://ws.fotowalla.com/Account")
    protected String accountTypeName;
    @XmlElement(name = "PasswordChangeDate", namespace = "http://ws.fotowalla.com/Account")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar passwordChangeDate;
    @XmlElement(name = "OpenDate", namespace = "http://ws.fotowalla.com/Account")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar openDate;
    @XmlElement(name = "CloseDate", namespace = "http://ws.fotowalla.com/Account")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar closeDate;
    @XmlElement(name = "Key", namespace = "http://ws.fotowalla.com/Account")
    protected String key;
    @XmlElement(name = "SecurityMessage", namespace = "http://ws.fotowalla.com/Account")
    protected String securityMessage;
    @XmlElement(name = "Emails", namespace = "http://ws.fotowalla.com/Account")
    protected Account.Emails emails;
    @XmlElement(name = "StorageSummary", namespace = "http://ws.fotowalla.com/Account")
    protected Account.StorageSummary storageSummary;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "version")
    protected Integer version;

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the newsletter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNewsletter() {
        return newsletter;
    }

    /**
     * Sets the value of the newsletter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNewsletter(Boolean value) {
        this.newsletter = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStatus(Integer value) {
        this.status = value;
    }

    /**
     * Gets the value of the accountMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountMessage() {
        return accountMessage;
    }

    /**
     * Sets the value of the accountMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountMessage(String value) {
        this.accountMessage = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountType(Integer value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountTypeName() {
        return accountTypeName;
    }

    /**
     * Sets the value of the accountTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountTypeName(String value) {
        this.accountTypeName = value;
    }

    /**
     * Gets the value of the passwordChangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPasswordChangeDate() {
        return passwordChangeDate;
    }

    /**
     * Sets the value of the passwordChangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPasswordChangeDate(XMLGregorianCalendar value) {
        this.passwordChangeDate = value;
    }

    /**
     * Gets the value of the openDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOpenDate() {
        return openDate;
    }

    /**
     * Sets the value of the openDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOpenDate(XMLGregorianCalendar value) {
        this.openDate = value;
    }

    /**
     * Gets the value of the closeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCloseDate() {
        return closeDate;
    }

    /**
     * Sets the value of the closeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCloseDate(XMLGregorianCalendar value) {
        this.closeDate = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the securityMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityMessage() {
        return securityMessage;
    }

    /**
     * Sets the value of the securityMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityMessage(String value) {
        this.securityMessage = value;
    }

    /**
     * Gets the value of the emails property.
     * 
     * @return
     *     possible object is
     *     {@link Account.Emails }
     *     
     */
    public Account.Emails getEmails() {
        return emails;
    }

    /**
     * Sets the value of the emails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account.Emails }
     *     
     */
    public void setEmails(Account.Emails value) {
        this.emails = value;
    }

    /**
     * Gets the value of the storageSummary property.
     * 
     * @return
     *     possible object is
     *     {@link Account.StorageSummary }
     *     
     */
    public Account.StorageSummary getStorageSummary() {
        return storageSummary;
    }

    /**
     * Sets the value of the storageSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account.StorageSummary }
     *     
     */
    public void setStorageSummary(Account.StorageSummary value) {
        this.storageSummary = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getId() {
        if (id == null) {
            return  0L;
        } else {
            return id;
        }
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getVersion() {
        if (version == null) {
            return  0;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EmailRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Principle" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="Secondary" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="Verified" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emailRef"
    })
    public static class Emails {

        @XmlElement(name = "EmailRef", namespace = "http://ws.fotowalla.com/Account")
        protected List<Account.Emails.EmailRef> emailRef;

        /**
         * Gets the value of the emailRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the emailRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmailRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Account.Emails.EmailRef }
         * 
         * 
         */
        public List<Account.Emails.EmailRef> getEmailRef() {
            if (emailRef == null) {
                emailRef = new ArrayList<Account.Emails.EmailRef>();
            }
            return this.emailRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Principle" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="Secondary" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="Verified" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address",
            "principle",
            "secondary",
            "verified"
        })
        public static class EmailRef {

            @XmlElement(name = "Address", namespace = "http://ws.fotowalla.com/Account")
            protected String address;
            @XmlElement(name = "Principle", namespace = "http://ws.fotowalla.com/Account")
            protected Boolean principle;
            @XmlElement(name = "Secondary", namespace = "http://ws.fotowalla.com/Account")
            protected Boolean secondary;
            @XmlElement(name = "Verified", namespace = "http://ws.fotowalla.com/Account")
            protected Boolean verified;

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress(String value) {
                this.address = value;
            }

            /**
             * Gets the value of the principle property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPrinciple() {
                return principle;
            }

            /**
             * Sets the value of the principle property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPrinciple(Boolean value) {
                this.principle = value;
            }

            /**
             * Gets the value of the secondary property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isSecondary() {
                return secondary;
            }

            /**
             * Sets the value of the secondary property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setSecondary(Boolean value) {
                this.secondary = value;
            }

            /**
             * Gets the value of the verified property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isVerified() {
                return verified;
            }

            /**
             * Sets the value of the verified property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setVerified(Boolean value) {
                this.verified = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StorageGBLimit" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="MonthlyUploadCap" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="UploadCount30Days" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="FormatRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="UploadSourceRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ImageYearRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "storageGBLimit",
        "monthlyUploadCap",
        "uploadCount30Days",
        "sizeGB",
        "compressedSizeGB",
        "imageCount",
        "formatRef",
        "uploadSourceRef",
        "imageYearRef"
    })
    public static class StorageSummary {

        @XmlElement(name = "StorageGBLimit", namespace = "http://ws.fotowalla.com/Account")
        protected double storageGBLimit;
        @XmlElement(name = "MonthlyUploadCap", namespace = "http://ws.fotowalla.com/Account")
        protected int monthlyUploadCap;
        @XmlElement(name = "UploadCount30Days", namespace = "http://ws.fotowalla.com/Account")
        protected int uploadCount30Days;
        @XmlElement(name = "SizeGB", namespace = "http://ws.fotowalla.com/Account")
        protected double sizeGB;
        @XmlElement(name = "CompressedSizeGB", namespace = "http://ws.fotowalla.com/Account")
        protected double compressedSizeGB;
        @XmlElement(name = "ImageCount", namespace = "http://ws.fotowalla.com/Account")
        protected int imageCount;
        @XmlElement(name = "FormatRef", namespace = "http://ws.fotowalla.com/Account")
        protected List<Account.StorageSummary.FormatRef> formatRef;
        @XmlElement(name = "UploadSourceRef", namespace = "http://ws.fotowalla.com/Account")
        protected List<Account.StorageSummary.UploadSourceRef> uploadSourceRef;
        @XmlElement(name = "ImageYearRef", namespace = "http://ws.fotowalla.com/Account")
        protected List<Account.StorageSummary.ImageYearRef> imageYearRef;

        /**
         * Gets the value of the storageGBLimit property.
         * 
         */
        public double getStorageGBLimit() {
            return storageGBLimit;
        }

        /**
         * Sets the value of the storageGBLimit property.
         * 
         */
        public void setStorageGBLimit(double value) {
            this.storageGBLimit = value;
        }

        /**
         * Gets the value of the monthlyUploadCap property.
         * 
         */
        public int getMonthlyUploadCap() {
            return monthlyUploadCap;
        }

        /**
         * Sets the value of the monthlyUploadCap property.
         * 
         */
        public void setMonthlyUploadCap(int value) {
            this.monthlyUploadCap = value;
        }

        /**
         * Gets the value of the uploadCount30Days property.
         * 
         */
        public int getUploadCount30Days() {
            return uploadCount30Days;
        }

        /**
         * Sets the value of the uploadCount30Days property.
         * 
         */
        public void setUploadCount30Days(int value) {
            this.uploadCount30Days = value;
        }

        /**
         * Gets the value of the sizeGB property.
         * 
         */
        public double getSizeGB() {
            return sizeGB;
        }

        /**
         * Sets the value of the sizeGB property.
         * 
         */
        public void setSizeGB(double value) {
            this.sizeGB = value;
        }

        /**
         * Gets the value of the compressedSizeGB property.
         * 
         */
        public double getCompressedSizeGB() {
            return compressedSizeGB;
        }

        /**
         * Sets the value of the compressedSizeGB property.
         * 
         */
        public void setCompressedSizeGB(double value) {
            this.compressedSizeGB = value;
        }

        /**
         * Gets the value of the imageCount property.
         * 
         */
        public int getImageCount() {
            return imageCount;
        }

        /**
         * Sets the value of the imageCount property.
         * 
         */
        public void setImageCount(int value) {
            this.imageCount = value;
        }

        /**
         * Gets the value of the formatRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the formatRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFormatRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Account.StorageSummary.FormatRef }
         * 
         * 
         */
        public List<Account.StorageSummary.FormatRef> getFormatRef() {
            if (formatRef == null) {
                formatRef = new ArrayList<Account.StorageSummary.FormatRef>();
            }
            return this.formatRef;
        }

        /**
         * Gets the value of the uploadSourceRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uploadSourceRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUploadSourceRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Account.StorageSummary.UploadSourceRef }
         * 
         * 
         */
        public List<Account.StorageSummary.UploadSourceRef> getUploadSourceRef() {
            if (uploadSourceRef == null) {
                uploadSourceRef = new ArrayList<Account.StorageSummary.UploadSourceRef>();
            }
            return this.uploadSourceRef;
        }

        /**
         * Gets the value of the imageYearRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imageYearRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImageYearRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Account.StorageSummary.ImageYearRef }
         * 
         * 
         */
        public List<Account.StorageSummary.ImageYearRef> getImageYearRef() {
            if (imageYearRef == null) {
                imageYearRef = new ArrayList<Account.StorageSummary.ImageYearRef>();
            }
            return this.imageYearRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "format",
            "sizeGB",
            "compressedSizeGB",
            "imageCount"
        })
        public static class FormatRef {

            @XmlElement(name = "Format", namespace = "http://ws.fotowalla.com/Account")
            protected String format;
            @XmlElement(name = "SizeGB", namespace = "http://ws.fotowalla.com/Account")
            protected Double sizeGB;
            @XmlElement(name = "CompressedSizeGB", namespace = "http://ws.fotowalla.com/Account")
            protected Double compressedSizeGB;
            @XmlElement(name = "ImageCount", namespace = "http://ws.fotowalla.com/Account")
            protected Integer imageCount;

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

            /**
             * Gets the value of the sizeGB property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getSizeGB() {
                return sizeGB;
            }

            /**
             * Sets the value of the sizeGB property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setSizeGB(Double value) {
                this.sizeGB = value;
            }

            /**
             * Gets the value of the compressedSizeGB property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getCompressedSizeGB() {
                return compressedSizeGB;
            }

            /**
             * Sets the value of the compressedSizeGB property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setCompressedSizeGB(Double value) {
                this.compressedSizeGB = value;
            }

            /**
             * Gets the value of the imageCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getImageCount() {
                return imageCount;
            }

            /**
             * Sets the value of the imageCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setImageCount(Integer value) {
                this.imageCount = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "year",
            "sizeGB",
            "compressedSizeGB",
            "imageCount"
        })
        public static class ImageYearRef {

            @XmlElement(name = "Year", namespace = "http://ws.fotowalla.com/Account")
            protected String year;
            @XmlElement(name = "SizeGB", namespace = "http://ws.fotowalla.com/Account")
            protected Double sizeGB;
            @XmlElement(name = "CompressedSizeGB", namespace = "http://ws.fotowalla.com/Account")
            protected Double compressedSizeGB;
            @XmlElement(name = "ImageCount", namespace = "http://ws.fotowalla.com/Account")
            protected Integer imageCount;

            /**
             * Gets the value of the year property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setYear(String value) {
                this.year = value;
            }

            /**
             * Gets the value of the sizeGB property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getSizeGB() {
                return sizeGB;
            }

            /**
             * Sets the value of the sizeGB property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setSizeGB(Double value) {
                this.sizeGB = value;
            }

            /**
             * Gets the value of the compressedSizeGB property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getCompressedSizeGB() {
                return compressedSizeGB;
            }

            /**
             * Sets the value of the compressedSizeGB property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setCompressedSizeGB(Double value) {
                this.compressedSizeGB = value;
            }

            /**
             * Gets the value of the imageCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getImageCount() {
                return imageCount;
            }

            /**
             * Sets the value of the imageCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setImageCount(Integer value) {
                this.imageCount = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="CompressedSizeGB" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "sizeGB",
            "compressedSizeGB",
            "imageCount"
        })
        public static class UploadSourceRef {

            @XmlElement(name = "Name", namespace = "http://ws.fotowalla.com/Account")
            protected String name;
            @XmlElement(name = "SizeGB", namespace = "http://ws.fotowalla.com/Account")
            protected Double sizeGB;
            @XmlElement(name = "CompressedSizeGB", namespace = "http://ws.fotowalla.com/Account")
            protected Double compressedSizeGB;
            @XmlElement(name = "ImageCount", namespace = "http://ws.fotowalla.com/Account")
            protected Integer imageCount;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the sizeGB property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getSizeGB() {
                return sizeGB;
            }

            /**
             * Sets the value of the sizeGB property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setSizeGB(Double value) {
                this.sizeGB = value;
            }

            /**
             * Gets the value of the compressedSizeGB property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getCompressedSizeGB() {
                return compressedSizeGB;
            }

            /**
             * Sets the value of the compressedSizeGB property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setCompressedSizeGB(Double value) {
                this.compressedSizeGB = value;
            }

            /**
             * Gets the value of the imageCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getImageCount() {
                return imageCount;
            }

            /**
             * Sets the value of the imageCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setImageCount(Integer value) {
                this.imageCount = value;
            }

        }

    }

}
