//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.07 at 09:21:34 PM BST 
//


package walla.datatypes.auto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AppMajorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AppMinorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AppCRC" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PlatformOS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PlatformType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OSMajorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OSMinorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="UserAppId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appKey",
    "appMajorVersion",
    "appMinorVersion",
    "appCRC",
    "platformOS",
    "platformType",
    "osMajorVersion",
    "osMinorVersion",
    "userAppId"
})
@XmlRootElement(name = "AppDetail", namespace = "http://ws.fotowalla.com/AppDetail")
public class AppDetail {

    @XmlElement(name = "AppKey", namespace = "http://ws.fotowalla.com/AppDetail", required = true)
    protected String appKey;
    @XmlElement(name = "AppMajorVersion", namespace = "http://ws.fotowalla.com/AppDetail")
    protected int appMajorVersion;
    @XmlElement(name = "AppMinorVersion", namespace = "http://ws.fotowalla.com/AppDetail")
    protected int appMinorVersion;
    @XmlElement(name = "AppCRC", namespace = "http://ws.fotowalla.com/AppDetail")
    protected long appCRC;
    @XmlElement(name = "PlatformOS", namespace = "http://ws.fotowalla.com/AppDetail", required = true)
    protected String platformOS;
    @XmlElement(name = "PlatformType", namespace = "http://ws.fotowalla.com/AppDetail", required = true)
    protected String platformType;
    @XmlElement(name = "OSMajorVersion", namespace = "http://ws.fotowalla.com/AppDetail")
    protected int osMajorVersion;
    @XmlElement(name = "OSMinorVersion", namespace = "http://ws.fotowalla.com/AppDetail")
    protected int osMinorVersion;
    @XmlElement(name = "UserAppId", namespace = "http://ws.fotowalla.com/AppDetail")
    protected long userAppId;

    /**
     * Gets the value of the appKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * Sets the value of the appKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppKey(String value) {
        this.appKey = value;
    }

    /**
     * Gets the value of the appMajorVersion property.
     * 
     */
    public int getAppMajorVersion() {
        return appMajorVersion;
    }

    /**
     * Sets the value of the appMajorVersion property.
     * 
     */
    public void setAppMajorVersion(int value) {
        this.appMajorVersion = value;
    }

    /**
     * Gets the value of the appMinorVersion property.
     * 
     */
    public int getAppMinorVersion() {
        return appMinorVersion;
    }

    /**
     * Sets the value of the appMinorVersion property.
     * 
     */
    public void setAppMinorVersion(int value) {
        this.appMinorVersion = value;
    }

    /**
     * Gets the value of the appCRC property.
     * 
     */
    public long getAppCRC() {
        return appCRC;
    }

    /**
     * Sets the value of the appCRC property.
     * 
     */
    public void setAppCRC(long value) {
        this.appCRC = value;
    }

    /**
     * Gets the value of the platformOS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformOS() {
        return platformOS;
    }

    /**
     * Sets the value of the platformOS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformOS(String value) {
        this.platformOS = value;
    }

    /**
     * Gets the value of the platformType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformType() {
        return platformType;
    }

    /**
     * Sets the value of the platformType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformType(String value) {
        this.platformType = value;
    }

    /**
     * Gets the value of the osMajorVersion property.
     * 
     */
    public int getOSMajorVersion() {
        return osMajorVersion;
    }

    /**
     * Sets the value of the osMajorVersion property.
     * 
     */
    public void setOSMajorVersion(int value) {
        this.osMajorVersion = value;
    }

    /**
     * Gets the value of the osMinorVersion property.
     * 
     */
    public int getOSMinorVersion() {
        return osMinorVersion;
    }

    /**
     * Sets the value of the osMinorVersion property.
     * 
     */
    public void setOSMinorVersion(int value) {
        this.osMinorVersion = value;
    }

    /**
     * Gets the value of the userAppId property.
     * 
     */
    public long getUserAppId() {
        return userAppId;
    }

    /**
     * Sets the value of the userAppId property.
     * 
     */
    public void setUserAppId(long value) {
        this.userAppId = value;
    }

}
